baseURL = "https://docs.makovako.xyz/"
title = "makovako doc's"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
    geekdocToC = 3
    geekdocSearchShowParent = true
    geekdocCollapseAllSections = true
    # geekdocMenuBundle = true